name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        description: 'Environment'
        required: true
        options:
           - Debug
           - Release

env:
  AZURE_WEBAPP_NAME: SimpleFrameworkApp.sln     # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'published'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore NuGet packages
      run: nuget restore ${{ env.AZURE_WEBAPP_NAME }}

    - name: Build
      run: msbuild ${{ env.AZURE_WEBAPP_NAME }} /p:Configuration=Release

    - name: Publish to folder
      run: msbuild ${{ env.AZURE_WEBAPP_NAME }} /p:Configuration=Release /p:EnvironmentName=${{ inputs.Environment }} /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ env.AZURE_WEBAPP_PACKAGE_PATH }} /p:PackageAsSingleFile=false

    - name: Retrieve publish profile for deployment
      id: publishProfileRetrieval
      run: |
        publishProfiles=$(az webapp deployment list-publishing-profiles \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group "${{ env.RESOURCE_GROUP }}" \
          --subscription ${{ vars.AZURE_SUBSCRIPTION_ID }} --xml)
        echo "::add-mask::$publishProfiles"
        echo "::set-output name=publishProfiles::$publishProfiles"

    - name: Deploy ${{ env.artifactName }} to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}
